#!/usr/bin/env ruby
$: << File.join(File.dirname(__FILE__), "../lib")
require 'pry'
require 'zeevex_cluster'
require 'zeevex_cluster/util/delayed'
require 'zeevex_cluster/util/future'
require 'zeevex_cluster/util/promise'
require 'zeevex_cluster/util/delay'

binding.pry
